///////////////////////////////////////////////////////////////////////////////
// File generated by HDevelop for HALCON/C++ Version 13.0.2.2
///////////////////////////////////////////////////////////////////////////////




#ifndef __APPLE__
#  include "HalconCpp.h"
#  include "HDevThread.h"
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONCpp/HalconCpp.h>
#    include <HALCONCpp/HDevThread.h>
#  else
#    include <HALCONCppxl/HalconCpp.h>
#    include <HALCONCppxl/HDevThread.h>
#  endif
#endif



using namespace HalconCpp;


// Chapter: Tools / Geometry
// Short Description: Sort tuple pairs. 
void sort_pairs (HTuple hv_T1, HTuple hv_T2, HTuple hv_SortMode, HTuple *hv_Sorted1, 
    HTuple *hv_Sorted2)
{

  // Local iconic variables

  // Local control variables
  HTuple  hv_Indices1, hv_Indices2;

  //Sort tuple pairs.
  //
  //input parameters:
  //T1: first tuple
  //T2: second tuple
  //SortMode: if set to '1', sort by the first tuple,
  //   if set to '2', sort by the second tuple
  //
  if (0 != (HTuple(hv_SortMode==HTuple("1")).TupleOr(hv_SortMode==1)))
  {
    TupleSortIndex(hv_T1, &hv_Indices1);
    (*hv_Sorted1) = hv_T1.TupleSelect(hv_Indices1);
    (*hv_Sorted2) = hv_T2.TupleSelect(hv_Indices1);
  }
  else if (0 != (HTuple(HTuple(hv_SortMode==HTuple("column")).TupleOr(hv_SortMode==HTuple("2"))).TupleOr(hv_SortMode==2)))
  {
    TupleSortIndex(hv_T2, &hv_Indices2);
    (*hv_Sorted1) = hv_T1.TupleSelect(hv_Indices2);
    (*hv_Sorted2) = hv_T2.TupleSelect(hv_Indices2);
  }
  return;
}
